name: lyra
description: AI Voice Assistant App powered by ChatGPT and DALL-E.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.1.1
  http: ^0.13.5
  flutter_tts: ^3.6.3
  animate_do: ^3.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons: 
  android: true
  ios: true
  image_path: "assets/lyra_logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/lyra_logo.png"
  
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/lyra_logo.png
    - assets/sounds/
  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf
          style: italic